version: "3"

services:
  api:
    build: ./api
    image: chat-api
    container_name: chat-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - ./cache:/cache
    command: uvicorn api.main:app --host 0.0.0.0 --reload
  ui:
    build: ./ui
    image: chat-ui
    container_name: chat-ui
    ports:
      - 5173:5173
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev --host 0.0.0.0