name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . -t my-image-name:$VERSION

      - name: Push the Docker image
        if: ${{ github.event_name == 'push' }}
        needs: 
        run: |
          docker login $DOCKER_HUB_USERNAME:$DOCKER_HUB_PASSWORD
          docker push my-image-name:$VERSION
